### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by alabotski** [pkdone/practical-mongodb-aggregations-book#3]
Hi
Can you add support download ready formatted book?
In pdf or epub extension

**Comment by pkdone** [comment]
Hi, my aim is to provide both PDF and EPUB downloads but currently have issues with the framework which prevents that. In the meantime, the print icon in the top right of book pages works ok and when you click it and select Print to PDF in your OS dialog box it will generate the whole book into PDF file (not perfectly formatted but still quite readable)

**Comment by pkdone** [comment]
Ok, I've now got paper and downloadable (PDF & EPUB) expanded versions of the book now published by Packt. You can buy them here: 

- https://www.packtpub.com/product/practical-mongodb-aggregations/9781835080641
- https://www.amazon.com/Practical-MongoDB-Aggregations-developing-aggregation-ebook/dp/B0CGVKYGPT
